### ISSUE TITLE
Breaking changes between 3.3.2 and 3.3.3

### ISSUE THREAD

**Issue by robrichard** [adriantoine/enzyme-to-json#101]
Version 3.3.3 changed the behavior regarding default props which breaks snapshots.

**Comment by adriantoine** [comment]
Hi @robrichard,

Yes it is made on purpose as `3.3.2` introduced breaking changes that should have been published as a major version and broke a lot of builds. `3.3.3` is reverting to the behaviour of `3.3.1`. I suggest you update your snapshots or wait for the version including default props to be released. `3.3.2` should have never been released.

Sorry for the inconvenience.
