### ISSUE TITLE
Bound function names no longer showing in snapshots

### ISSUE THREAD

**Issue by alistaircolling** [adriantoine/enzyme-to-json#103]
Hi there, I recently upgraded a project:

**From**
- React 15.4.2
- Enzyme 2.8.2
- enzyme-to-json 1.5.1

**To**
- React 16.3.1
- Enzyme 3.3.0
- enzyme-to-json 3.3.3

Now lots of tests are failing due to snapshots not matching:

```
  + expected - actual
      -    onBlur={[Function]}
      -    onChange={[Function]}
      +    onBlur={[Function bound onBlurHandler]}
      +    onChange={[Function bound onChangeHandler]}
```

Is this expected behaviour? I guess tests are more brittle if the handler names are there.
Thanks :)

**Comment by rosath** [comment]
I have the same issue with:

- React 16.4.0
- Enzyme 3.3.0
- enzyme-to-json 3.3.4

**Comment by michelts** [comment]
Jest [stopped to show function names](https://jestjs.io/blog/2016/10/03/jest-16.html#snapshot-updates) in snapshots. [This comment](https://github.com/facebook/jest/issues/2580#issuecomment-272405197) from another discussion expose why.

There is a [work in progress to offer an alternative](https://github.com/facebook/jest/pull/8668), but it is not done yet.

In your specific case, I would recommend to test the handlers explicitly (e.g. get a wrapper and simulate blur and change).

**Comment by VincentLanglet** [comment]
Jest issue then not enzyme-to-json.
