### ISSUE TITLE
Remove `Object {` from snapshots

### ISSUE THREAD

**Issue by rattrayalex-stripe** [adriantoine/enzyme-to-json#104]
Hello & thanks for an awesome library!

I assume this feature is intentional, but I find it a bit noisy: 

```jsx
<Foo
  nestedObj={
    Object {
      "a": Object {
        "b": "c",
      },
    }
  }
/>
```
I would prefer: 
```jsx
<Foo
  nestedObj={{
    "a": {
      "b": "c",
    },
  }}
/>
```

I would be happy with an option to opt-in to this feature, as its release would break many snapshots in the wild. 

Thoughts?

**Comment by VincentLanglet** [comment]
`Array` and `Object` keyword are coming from jest. I don't think we can do something about it.
