### ISSUE TITLE
Snapshot issue for Fragment

### ISSUE THREAD

**Issue by Mayank009** [adriantoine/enzyme-to-json#111]
Two different snapshots are getting generated using shallow for below component

**Component**:
`import React, { Component, Fragment } from 'react';
<Fragment>
	<Header location={location} matchUrl={match.url} />
	<section className="ps">
		<Switch>
			<Route path={`${matchUrl}/topics`} component={TopicsContainer} />
			<Route path={`${matchUrl}/people`} component={PeopleContainer} />
			<Route path={`${matchUrl}/tools-and-frameworks`} component={ToolsAndFrameworksContainer} />
			<Route path={`${matchUrl}`} component={HomeContainer} />
		</Switch>
	</section>
</Fragment>`

**Snapshot 1**:
`<React.Fragment><Headerlocation={Object {"pathname": "/practices/test_9995",} } matchUrl="/practices/test_9995"/><section className="ps"><Switch><Routecomponent={[Function]}path="/practices/test_9995/topics"/><Routecomponent={[Function]}path="/practices/test_9995/people"/><Routecomponent={[Function]}path="/practices/test_9995/tools-and-frameworks"/><Routecomponent={[Function]}path="/practices/test_9995"/> </Switch></section></React.Fragment>`

**Snapshot 2**:

`<Fragment><Headerlocation={Object {"pathname": "/practices/test_9995",} } matchUrl="/practices/test_9995"/><section className="ps"><Switch><Routecomponent={[Function]}path="/practices/test_9995/topics"/><Routecomponent={[Function]}path="/practices/test_9995/people"/><Routecomponent={[Function]}path="/practices/test_9995/tools-and-frameworks"/><Routecomponent={[Function]}path="/practices/test_9995"/> </Switch></section></Fragment>`

What could be the possible reason for <React.Fragment></React.Fragment> in first and <Fragment></Fragment> in latter for same component?

**Comment by Mayank009** [comment]
When I debugged component for both snapshots I got outputs as below.

Note: I used debug function as below
`const component = shallow(<AppLayout />);`
`component.debug();`

**Snapshot 1**
`<Symbol(react.fragment)><Header location={{...}} matchUrl="/practices/test_9995" /><section className="ps"><Switch><Route path="/practices/test_9995/topics" component={[Function: Connect]} /><Route path="/practices/test_9995/people" component={[Function: Connect]} /><Route path="/practices/test_9995/tools-and-frameworks" component={[Function: Connect]} /><Route path="/practices/test_9995" component={[Function: Connect]} /></Switch></section></Symbol(react.fragment)>`

**Snapshot 2**

`<Fragment><Header location={{...}} matchUrl="/practices/test_9995" /><section className="ps"><Switch><Route path="/practices/test_9995/topics" component={[Function: Connect]} /><Route path="/practices/test_9995/people" component={[Function: Connect]} /><Route path="/practices/test_9995/tools-and-frameworks" component={[Function: Connect]} /><Route path="/practices/test_9995" component={[Function: Connect]} /></Switch></section></Fragment>`

Any help on how can I debug reason for <Symbol(react.fragment)> in first whereas <Fragment> in latter debug output?

**Comment by bsingr** [comment]
We are facing the same problem here. However, we get different results on different test machines:

- No diff issue on macOS
- Diff issue on Debian8/Docker (GitlabCI)

@Mayank009, what OS and npm-package versions do you run?

**Comment by bsingr** [comment]
Just curious, could this be due to difference between those two:

- https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js#L363
- https://github.com/facebook/jest/blob/v23.4.2/packages/pretty-format/src/plugins/react_element.js#L47

**Comment by Mayank009** [comment]
@bsingr, 
Snapshot 1: 
 OS: MacOS
 Npm Version: 6.3.0 
Snapshot 2:
 OS: Alpine (Docker Container)
 Npm Version: 5.6.0.

**Comment by SamSamskies** [comment]
I had this same issue. For the machine producing snapshot 1, make sure you update to the latest enzyme (v3.4.1), enzyme-to-json (v3.3.4), and enzyme-adapter-react-16 (v1.2.0). That fixed it for me. Not sure which package was causing the issue as I updated all of them at the same time. Also, not sure why my machine was out of sync with my CI server despite having a package-lock.json.

**Comment by Mayank009** [comment]
@SamSamskies it's fixed now. Thanks.
