### ISSUE TITLE
Typescript config: make `noKey` optional

### ISSUE THREAD

**Issue by siebertm** [adriantoine/enzyme-to-json#115]
In a typescript project, I'm running into the following error:

```
Property 'noKey' is missing in type '{ mode: "shallow"; }'.

expect(toJson(wrapper, { mode: 'shallow' })).toMatchSnapshot()
```

This stems from the property `noKey` being a non-optional boolean in the typescript definition. IMO, this should be an optional argument, as it is also optional for the pure-js version, correct?

**Comment by siebertm** [comment]
Thank you @samstradling !

@adriantoine would it be possible to do a patch release, also?

**Comment by VincentLanglet** [comment]
Solved in the new release
