### ISSUE TITLE
[React.memo] Memo renders as [object Object]

### ISSUE THREAD

**Issue by tommarien** [adriantoine/enzyme-to-json#119]
this fixes it in the same way as pureComponents are treated

```js
toJson(wrapper, {
      map: (node) => {
        if (typeof node.type === 'object' && node.type.$$typeof === Symbol.for('react.memo')) {
          return Object.create(node, {
            type: {
              configurable: true,
              enumerable: true,
              value: (node.type).type.name,
            },
          });
        }

        return node;
      },
    })
```

**Comment by tommarien** [comment]
With latest release 3.3.5 you only see <React.memo {...props} /> not the underlying component. The above code threats is as if memo was not there, the new release threats as if the underlying component makes no difference. Think about connect hoc, it renders as <Connected(Component)/> for a reason ;)

**Comment by VincentLanglet** [comment]
I can not understand this issue.

If you have a problem explain it most clearly. If you have an improvement to propose, open a PR.
