### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by Fandekasp** [adriantoine/enzyme-to-json#121]
Please follow semantic releases and write release notes. There hasn't been any notes in the past 5 releases, and studying each release diff takes more time than many people can afford.

For the latest release, the note `support React.lazy, React.memo and React.suspense` would have been perfect

**Comment by adriantoine** [comment]
Hi @Fandekasp, you're absolutely right, I have added [release notes](https://github.com/adriantoine/enzyme-to-json/releases) for the last 5 releases.
