### ISSUE TITLE
Incorrect peer dependency version

### ISSUE THREAD

**Issue by ersel** [adriantoine/enzyme-to-json#122]
After the last update to `enzyme-to-json` **3.3.5** our tests started failing with a mixture of:

`TypeError: Cannot read property '$$typeof' of undefined`

and also

`TypeError: Cannot convert a Symbol value to a string`

These problems only occur if you're using an `enzyme` version **3.3.0** or earlier, so I believe peer dependency listed in `package.json` is no longer correct after the last update. 

Enzyme peer dependency version should be `^3.4.0`.

**Comment by ersel** [comment]
What's your enzyme version @alanyinjs ?Try upgrading to a newer version if you are below 3.3.0.

**Comment by alanyinjs** [comment]
@ersel I am using enzyme@3.3.0. I'm just using enzyme-to-json@3.3.4 as a temporary fix 😄

**Comment by ersel** [comment]
You should upgrade `enzyme` @alanyinjs to something higher than 3.3.0 @alanyinjs

**Comment by RiccardoF** [comment]
When I upgraded to 3.3.5 I still have the error: 
`TypeError: Cannot read property '$$typeof' of undefined`

With the version 3.3.4 is fine.

**Comment by mcguiretj18** [comment]
Update to the latest enzyme package worked for me

**Comment by VincentLanglet** [comment]
https://github.com/adriantoine/enzyme-to-json/pull/123 is merged, I need to deploy a new version
