### ISSUE TITLE
render() returns null for <script> tag

### ISSUE THREAD

**Issue by adrienWeiss** [adriantoine/enzyme-to-json#133]
Hi 👋 

Any `<script />` tag is ignored in the snapshots
```js
it('test', () => {
    const tree = render(
      <div>
        <span>{'hello'}</span>
        <script dangerouslySetInnerHTML={{ __html: 'console.log("foo")' }} />
      </div>
    );
    expect(tree).toMatchInlineSnapshot(`
<div>
  <span>
    hello
  </span>
</div>
`);
  });
```
From what I understand it is because `script` is not a `type: 'tag'` but `type: 'script'`, and gets skipped here https://github.com/adriantoine/enzyme-to-json/blob/df30a5ace977c97fb42a6164a9f47af618ccf368/src/render.js#L10
Changing this line to `if (child.type === 'tag' || child.type === 'script') {` works but may not be without consequences.

If you think this is a correct fix I can try & submit a PR 
Thank you

**Comment by VincentLanglet** [comment]
PR are welcomed. Is there other `type` not handled ?

**Comment by adrienWeiss** [comment]
I'm not quite sure, all other tags I've encountered work fine. 
I'm send a PR right now, thank you
