### ISSUE TITLE
Deep mode includes ForwardRef

### ISSUE THREAD

**Issue by fongandrew** [adriantoine/enzyme-to-json#135]
The [deep mode documentation](https://github.com/adriantoine/enzyme-to-json/blob/master/docs/modes.md#deep-mode) states that the rendered test object contains only DOM nodes.

However, when doing `toJson(mount(<Component />), { mode: 'deep' })`, the rendered snapshot includes any `<ForwardRef>` components created by [`React.forwardRef`](https://reactjs.org/docs/forwarding-refs.html).

Sample output:

```
<span
  className="container"
>
  <ForwardRef
    className="slider"
    max={1}
    min={0}
    step={0.01}
    value={0.3}
  >
    <ForwardRef
      className="slider"
      hasKeyboardFocus={false}
      max={1}
      min={0}
      step={0.01}
      value={0.3}
    >
      <input
        className="slider"
        max={1}
        min={0}
        onChange={[Function]}
        step={0.01}
        type="range"
        value={0.3}
      />
    </ForwardRef>
  </ForwardRef>
</span>
```

**Comment by trollepierre** [comment]
Same issue when I shallow(<div><MyForwardedRefComponent/></div>), I got `<ForwardRef />` in my snapshot...

**Comment by trollepierre** [comment]
My bad, it looks like the issue does not comes from enzyme-to-json (I remove the serializer in my test, and I got the same error)

**Comment by puncha** [comment]
I also encounter the issue and it is not very stable. Sometimes, it is `<Styled(WithTheme(Typographic))` sometimes, it is `ForwardRef`.

**Comment by trollepierre** [comment]
are you sure, it is related to enzyme-to-json?

**Comment by puncha** [comment]
No, I don't why my edits to my comments were gone. Actually, after I upgraded enzyme packages, the issue goes away.

**Comment by VincentLanglet** [comment]
Related to enzyme then.
