### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by adriantoine** [adriantoine/enzyme-to-json#143]
Hi!

As everyone has probably noticed, I am not really working on this library anymore. I wished I could but I somehow got very busy in my life.

First I'd like to apologise to anyone impacted by the lack of support, and then I'd like to find a maintainer to help sort out issues and review PRs, and eventually take ownership of this repository.

Anyone interested, send me an email to adriantoine@gmail.com, don't be shy!

**Comment by VincentLanglet** [comment]
I will try to help but I have nothing against a little help.

**Comment by adriantoine** [comment]
@vincentlanglet has generously proposed to help me work on this repo so I'm not looking for contributors anymore.

Thanks for helping @vincentlanglet, I'm so grateful!!!
