### ISSUE TITLE
moving from 3.4.0 to 3.4.1 breaks snapshots

### ISSUE THREAD

**Issue by tomatau** [adriantoine/enzyme-to-json#150]
Output of a snapshot from a connected custom component in 3.4.0:

```
<Connect(CustomComponent) />
```

The output of a snapshot from the same connected custom component in  3.4.1:

```
<React.Memo />
```

A patch update shouldn't have this sort of breaking change. The utility of 3.4.0 is better than 3.4.1 as well as it conveys more information about the component.

**Comment by VincentLanglet** [comment]
Need to revert https://github.com/adriantoine/enzyme-to-json/pull/145

**Comment by VincentLanglet** [comment]
I did it in release 3.4.2

The PR was made to fix this issue.
https://github.com/adriantoine/enzyme-to-json/issues/137

`<React.Memo />` instead of `<Connect(CustomComponent) />` is not great indeed.

I'd like to have `<React.Memo(CustomComponent) />`

**Comment by tomatau** [comment]
Thanks, 3.4.2 is back to non-breaking changes.
