### ISSUE TITLE
Undefined properties are rendered into snapshot

### ISSUE THREAD

**Issue by eskimoblood** [adriantoine/enzyme-to-json#21]
Not sure if this is a bug or a feature but after updating to the latest version all my snapshots contains `someProp={undefined}` for all props that are not defined in the test.

**Comment by adriantoine** [comment]
Thanks for reporting! I'll have a look as soon as I can.

**Comment by existentialism** [comment]
@adriantoine it looks like this was changed with switchover to use enzyme's utils,

before:
https://github.com/adriantoine/enzyme-to-json/commit/0e06c679#diff-1fdf421c05c1140f6d71444ea2b27638L14

after:
https://github.com/adriantoine/enzyme-to-json/blob/master/src/shallow.js#L34

I pushed a PR with a test!
