### ISSUE TITLE
Use wrapper.getNode() instead of wrapper.node

### ISSUE THREAD

**Issue by jwbay** [adriantoine/enzyme-to-json#27]
Enzyme recently picked up changes in v2.6.0 that remove the need for .update() in the shallow wrapper for a lot of cases. It accomplishes this by replacing the node and nodes properties with functions (getNode and getNodes) that always return the latest output of the underlying shallow renderer.

To keep back-compat with other versions of enzyme, one could simply check for .getNode and fall back to .node if it's not there.

Example:
```jsx
const wrapper = shallow(<MyComponent />);
wrapper.find(Child).props().methodThatSetsStateOnMyComponent();
wrapper.update(); //shallow DOM won't be updated in the snapshot without this
expect(shallowToJson(wrapper)).toMatchSnapshot();
```

With the proposed change, we wouldn't need the .update() call.

**Comment by adriantoine** [comment]
Hi @jwbay, sorry for the delay, it looks interesting, are you interested in making a pull request?
