### ISSUE TITLE
input types with checked={true} aren't rendering checked

### ISSUE THREAD

**Issue by solomon23** [adriantoine/enzyme-to-json#37]
I can't seem to get enzyme to render with the checked attribute of an input.  I've tried:

`<input type="checkbox" checked="checked" value="party" id="party-button" disabled="disabled" />`

and it'll render as (without the checked):

`<input disabled="" id="party-button" type="checkbox" value="party" />`

I tried these variations and they all render the same thing:

`<input type="checkbox" checked={true} value="party" id="party-button" disabled />`
`<input type="checkbox" checked="checked" value="party" id="party-button" disabled={true} />`

**Comment by adriantoine** [comment]
Hi @solomon23, thanks for raising the issue, I'll have a look as soon as I can, sorry for the delay!

**Comment by adriantoine** [comment]
I'm not able to reproduce this issue, if you can still reproduce it, please create a minimal repository where the issue is reproduceable.
