### ISSUE TITLE
Serialize style attributes as style={[object Object]}

### ISSUE THREAD

**Issue by dziamid** [adriantoine/enzyme-to-json#39]
I'd love to ignore some attributes when a component is serialized, for the purpose of keeping its snapshot focused and not cluttered with stuff like inline styles 

For example:
```
        <Dropzone multiple={false} accept="image/jpeg,image/png" onDrop={this.handleImageDrop}>
          <ContentAdd style={addBtnStyle} />
        </Dropzone>
```
Would serialize into:
```
<Dropzone
  accept="image/jpeg,image/png"
  multiple={false}
  onDrop={[Function]}>
  <ContentAdd
    style={
      Object {
        "color": "#1ac5c0",
        "height": 48,
        "left": "33px",
        "position": "absolute",
        "top": "33px",
        "width": 48,
      }
    } />
</Dropzone>
```

While i'd prefer:
```
<Dropzone
  accept="image/jpeg,image/png"
  multiple={false}
  onDrop={[Function]}>
  <ContentAdd 
     style={[object Object]}/> 
</Dropzone>
```

**Comment by pedrottimark** [comment]
@dziamid Your comments are welcome in a conversation about a potential general solution to matching a subset of attributes/properties at https://github.com/facebook/jest/issues/2202#issuecomment-268347718

**Comment by adriantoine** [comment]
Hi @dziamid, that's interesting but it's not really a bug with `enzyme-to-json` but a bug with Jest snapshots and how [`pretty-format`](https://github.com/facebook/jest/tree/master/packages/pretty-format) processes them! Thanks for the link @pedrottimark
