### ISSUE TITLE
Handle wrappers with multiple nodes

### ISSUE THREAD

**Issue by wuct** [adriantoine/enzyme-to-json#40]
This issue is probably related to #30.

When we invoke `find()` on enzyme's wrapper and get multiple nodes in return, `enzyme-to-json` only handles the first node.

For example: 

```JS
const App = () => (
  <div>
    <ul>
      <li>0</li>
      <li>1</li>
    </ul>
  </div>
);

const wrapper = mount(App);
```

When I call

```JS
expect(renderToJson(wrapper.find('li'))).toMatchSnapshot();
```

I expects to get something like

```JS
Array[
  <li>0</li>,
  <li>1</li>
]
```

but I get

```JS
<li>0</li>
```

It's because [this line](https://github.com/adriantoine/enzyme-to-json/blob/master/src/mount.js#L54)

We can change this behavior by checking the length of the wrapper first. In my mind, it would be something like:

```js
if (wrapper.length > 1) {
  wrapper.nodes.map(toJson)
} else {
  toJson(wrapper.node)
}
```

I would like to create a PR with related tests if this looks good to you.

**Comment by adriantoine** [comment]
Hi! Thanks for raising the issue, I would definitely like to see a PR for that! #30 was fixed but your bug is more about handling multiple nodes in output, so it's a bit different.
