### ISSUE TITLE
0 value is not serialized

### ISSUE THREAD

**Issue by benmvp** [adriantoine/enzyme-to-json#44]
Hi! Thanks for the wonderful work on this package! I prefer it to `react-test-renderer` because all of my tests leverage enzyme so it's one single way of doing things.

However, I believe I stumbled across a bug where a value of just `0` as children does not get serialized to JSON. Here's a minimal contrived example:

```js
it('dummy', () => {
    const TestComponent = ({number = 0}) => (
        <div>{number}</div>
    );

    let wrapper = mount(<TestComponent />);

    console.log(toJson(wrapper.find('div')));

   // this passes
    expect(wrapper.find('div').text()).toBe('0');
});
```

In the console:

```js
    Object {
      type: 'div',
      props: Object {},
      children: null,
      '$$typeof': Symbol(react.test.json) }
```

Interestingly enough, if I do `number.toString()` it works as expected. So something somewhere is doing a falsy check 😄 

Thanks!

**Comment by adriantoine** [comment]
Hi @benmvp! Thanks for raising the issue, it is an interesting one 😊 Probably a falsy check as you said, I'll have a look!

**Comment by adriantoine** [comment]
That's fixed now, it will be released in the next patch version!
