### ISSUE TITLE
child Components are unnamed when jest run with --coverage flag

### ISSUE THREAD

**Issue by tylercrosse** [adriantoine/enzyme-to-json#51]
I get a different snapshot depending on whether Jest is run with --coverage. Specifically, when Jest is run with `--coverage` some but not all of the child components appear simply as `<Component />` in the snapshot. When run without the `--coverage` flag all of the child Components appear in the snapshot with the correct name. Additionally, the components that appear as `<Component />` are all stateless functional components written as arrow functions. The child components that retain their name regardless of the coverage flag are class components. I've had a lot of trouble trying to reproduce this issue in a mock repo, but thought it would still be helpful to put it on the project's radar. I can currently avoid the issue by always running tests with or without the coverage flag, but when I switch between the two I need to also update snapshots.

**Comment by adriantoine** [comment]
Hi!

Thanks for reporting the issue. It is a known issue to be fixed on Istanbul, see https://github.com/adriantoine/enzyme-to-json/issues/19#issuecomment-278634889.

**Comment by tylercrosse** [comment]
Thanks! Sorry to waste your time. I missed that in my search before filing this issue.

**Comment by adriantoine** [comment]
No problem, thanks for reporting!
