### ISSUE TITLE
Package is broken with enzyme 2.8.1

### ISSUE THREAD

**Issue by aaronmcadam** [adriantoine/enzyme-to-json#52]
Using the latest `enzyme` `master`, which includes [fixes for React 15.5](https://github.com/airbnb/enzyme/pull/876)  raises the following error when running tests:

```
Cannot find module 'enzyme/build/ShallowWrapper' from 'utils.js'
```

I'll see if I can raise a PR to fix this once I figure out where the `ShallowWrapper` has moved to

**Comment by adriantoine** [comment]
Hi,

Thanks for the report, I'll have a look!

**Comment by aaronmcadam** [comment]
I forgot to mention that I'm using the latest version of `react` in my project. I'm not sure right now if the upgrade in `React` has moved something, or `enzyme` has.

**Comment by adriantoine** [comment]
That's a bit strange, I can't replicate it locally 🤔

**Comment by aaronmcadam** [comment]
@adriantoine Have you tried it with `react` `^15.5`?

**Comment by adriantoine** [comment]
Yep, I'm using react@15.5.4 and enzyme@2.8.0

**Comment by aaronmcadam** [comment]
Could you try setting your `package.json` to use `airbnb/enzyme`?

**Comment by aaronmcadam** [comment]
`react-addon-test-utils` should also be removed I think

**Comment by adriantoine** [comment]
If you do that you won't have the built files in the `build` folder, unless you run the build manually from your `node_modules` folder.

**Comment by adriantoine** [comment]
The [latest version of Enzyme](https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md#280) doesn't fix React warnings, does it?

The PR you mentioned above has been merged but the new version hasn't been released.

**Comment by aaronmcadam** [comment]
Yeah, they're releasing a new version soon. I raised this issue to raise visibility

**Comment by adriantoine** [comment]
Ok fine, if you are using `airbnb/enzyme` in your `package.json` you need to build Enzyme manually in your `node_modules` folder so that the files are built to the `build` folder.

**Comment by aaronmcadam** [comment]
Yeah, I thought that might be case when using a git source. I'm trying a few different things to nail down my issues, sorry for the confusion 😅

**Comment by adriantoine** [comment]
Yeah I have just tried that actually:
- Set your `package.json` dependency to `airbnb/enzyme`
- `npm install`
- `cd node_modules/enzyme`
- `npm install`
- `npm run build`

Then run your test again and it should work.

I'm closing this but feel free to comment here if it doesn't work once they've released that new version!

**Comment by aaronmcadam** [comment]
Thanks @adriantoine!

**Comment by adriantoine** [comment]
Reopening as there is indeed an error with the latest version of Enzyme (`2.8.1`):

```
  ● Test suite failed to run

    Cannot find module 'react-test-renderer/shallow' from 'react-compat.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at node_modules/enzyme/build/react-compat.js:151:34
      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:219:5)
```

**Comment by adriantoine** [comment]
Ok well I just need to install `react-dom` and `react-test-renderer` in the dev dependencies, closing again. 😄

**Comment by aaronmcadam** [comment]
Great, I'll give that a go tomorrow, thanks
