### ISSUE TITLE
Default props visible in shallow snapshot

### ISSUE THREAD

**Issue by mpodlasin** [adriantoine/enzyme-to-json#55]
Hi.

I have two components:

```javascript
const A = props => <div><B firstProps="a" /></div>;
```

```javascript
const B = props => <div />;

B.defaultProps = {
  secondProps: "b"
};
```

Snapshot of `A` I would expect:
```
<div>
  <B
    firstProps="a" />
</div>
```

Snapshot of `A` I got:
```
<div>
  <B
    firstProps="a"
    secondProps="b" />
</div>
```

Note how `B`s `defaultProps` are visible in shallow render of `A`, even though I did not pass them in `A`. This is very bad, since it exposes internals of `B`. When I change implementation of `B` it should only affect `B`s tests (this is the whole reason why I use shallow render), but currently if I change `defaultProps` it will affect tests of every component that uses `B`.

Only props really passed in `A` should be visible in snapshot.

Thoughts?

Have a good day, everyone. ;)

**Comment by adriantoine** [comment]
Hi!

Thanks for raising the issue, that's an interesting one. I agree that `A`'s snapshots shouldn't render `B`'s internals, my only concern is to check how Enzyme wrappers work. If `shallow(<A />).find('B').props()` returns `firstProps` and `secondProps`, there's no way I can exclude `secondProps` from the snapshot, and it might be an Enzyme bug as I wouldn't expect that to return default props.

I'll have a look when I have time.

**Comment by Podlas29** [comment]
I am up for tinkering myself and sending PR, if it's possible to provide fix. Just wanted to ask if you really consider it a bug.

**Comment by Podlas29** [comment]
Aaah, it seems that it is React that puts defaultProps in actual props as early as possible, so there are here from the very beginning (when React.createElement is called):

https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L183

Could we consider getting rid of them by hand? For example check at some point if component has defaultProps and if it has, remove all of such values by hand from actual props object?

**Comment by madou** [comment]
Hmm that's not good, I'll have look at fixing this.

**Comment by renet** [comment]
Sorry, but this seems to be a bug that newly came to enzyme/enzyme-to-json/React(?). We had shallow snapshots with enzyme-to-json before, that did **not** contain the default props. Any idea, why this is a new issue and what caused this?
