### ISSUE TITLE
key prop not visible in snapshot

### ISSUE THREAD

**Issue by lsentkiewicz** [adriantoine/enzyme-to-json#58]
If I add a `key` prop, it's not serialized to the snapshot.

Steps
- Add test `expect(<div />).toMatchSnapshot()`
- Update it `expect(<div key={1} key2={1} />).toMatchSnapshot()`
Result
![image](https://cloud.githubusercontent.com/assets/4478684/26629602/601dbb6c-4603-11e7-9b9f-dd9841b8e60a.png)

Expected:
Diff should show also `+ key={1}`

Snapshot serializer in jest-config.json
```
"snapshotSerializers": ["<rootDir>/node_modules/jest-serializer-enzyme"]
```
jest: 20.0.4
jest-serializer-enzyme: 1.0.0
enzyme-to-json: 1.5.1

**Comment by adriantoine** [comment]
Hi @lsentkiewicz!

Sorry for the delay, I just looked and it seems that Enzyme doesn't return the `key` prop when using the [`.props()`](https://github.com/airbnb/enzyme/blob/4d1517ab01c01011d7e7d1b4e9ae4201cd23268d/docs/api/ReactWrapper/props.md) helper, it is returned by a separate helper [`.key()`](https://github.com/airbnb/enzyme/blob/48712015e7709da63fe83a90fa3efb3a29dbb648/docs/api/ReactWrapper/key.md).

I will add the `key` prop to the snapshot and an option to disable it as some projects might not want to check that prop.
