### ISSUE TITLE
Does not generate Snapshot

### ISSUE THREAD

**Issue by ishantoberoi** [adriantoine/enzyme-to-json#61]
Getting error: Error: Invalid Chai property: toMatchSnapshot

import toJson from 'enzyme-to-json';

describe('Component Snapshot', () => {
          const wrapper = mount(\<Component /\>);
         const instance = wrapper.instance();

it('should generate shapshot', () => {
      expect(toJson(wrapper)).toMatchSnapshot()
  });

});

**Comment by adriantoine** [comment]
Hi,

```
Error: Invalid Chai property: toMatchSnapshot
```

It seems like you are trying to use `toMatchSnapshot` with Chai rather than Jest, please have a look at how to use Jest: https://facebook.github.io/jest/docs/getting-started.html.

**Comment by ishantoberoi** [comment]
Hi @adriantoine 

I wanted to know, where is this toMatchSnapshot coming from, in the examples stated here
https://www.npmjs.com/package/enzyme-to-json

I believe it is not mentioned that it is using jest

**Comment by adriantoine** [comment]
Hi @ishantoberoi,

Yes it is written in the description of the package: "Convert Enzyme wrappers to a format compatible with **Jest** snapshot testing."
