### ISSUE TITLE
When should I use toJson()?

### ISSUE THREAD

**Issue by IgorGee** [adriantoine/enzyme-to-json#73]
It seems like I can generate snapshots just fine without using `toJson`.

```
const component = shallow(<Component />)
expect(component).toMatchSnapshot()
```

Is this a valid way to use the serializer?

**Comment by adriantoine** [comment]
If you use the serializer, you don't need the `toJson` function to generate snapshots. `toJson` was originally made when Jest didn't support serializers.

You still might want to use `toJson` if you need to use the options.
