### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by vlad-zhukov** [adriantoine/enzyme-to-json#75]
There are few tests that render a single component with a `key` prop and expect it to be snapshotted, for example this one: [test](https://github.com/adriantoine/enzyme-to-json/blob/master/tests/mount.test.js#L119:L122) and [snapshot](https://github.com/adriantoine/enzyme-to-json/blob/master/tests/__snapshots__/mount.test.js.snap#L399).

**Comment by adriantoine** [comment]
Good point, I'll have a look.
