### ISSUE TITLE
Expose node to map function

### ISSUE THREAD

**Issue by kesne** [adriantoine/enzyme-to-json#82]
I noticed the new map function, which is super useful! However, it has limited use with the values that are provided. Something that might be useful would be exposing the raw node, so that you just have more information available to work with, and could do things like stripping defaultProps.

**Comment by adriantoine** [comment]
Hi!

Thanks for the suggestion! I was thinking about doing that yeah, it would be pretty hard to implement though. 

I'd definitely accept a PR for that but I don't have time to work on it right now.
