### ISSUE TITLE
toJson signature requires update

### ISSUE THREAD

**Issue by manu-st** [adriantoine/enzyme-to-json#85]
In the version 2.6 of TypeScript, they changed the way they perform type checking for function (see https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#strict-function-types). As a result code using `toJson` with a generic version of ComponentWrapper will not compile.

```
[ts]
Argument of type 'ReactWrapper<AppStore, {}>' is not assignable to parameter of type 'CommonWrapper<{}, {}>'.
  Types of property 'filterWhere' are incompatible.
    Type '(predicate: (wrapper: ReactWrapper<AppStore, {}>) => boolean) => ReactWrapper<AppStore, {}>' is not assignable to type '(predicate: (wrapper: CommonWrapper<{}, {}>) => boolean) => CommonWrapper<{}, {}>'.
      Types of parameters 'predicate' and 'predicate' are incompatible.
        Types of parameters 'wrapper' and 'wrapper' are incompatible.
          Type 'ReactWrapper<AppStore, {}>' is not assignable to type 'CommonWrapper<{}, {}>'.
```

**Comment by manu-st** [comment]
The solution seems to add the following to index.d.ts:
```
declare function toJson<P, V>(wrapper: CommonWrapper<P,V>, options?: Options): Json;
```

**Comment by adriantoine** [comment]
Hi @manu-st,

Thanks for the suggestion, it looks good, would you like to submit a Pull Request?

**Comment by adriantoine** [comment]
If you don't know how to do it, please check [CONTRIBUTING.md](https://github.com/adriantoine/enzyme-to-json/blob/master/.github/CONTRIBUTING.md).

**Comment by manu-st** [comment]
Just made the PR, see #86
