### ISSUE TITLE
Arrays not handled properly

### ISSUE THREAD

**Issue by donatasbacius** [adriantoine/enzyme-to-json#87]
Was upgrading an app to React@16 and came across what seems to be a bug with the latest `enzyme-to-json` (or [enzyme](https://github.com/adriantoine/enzyme-to-json/blob/master/src/shallow.js#L11)) where [snapshots for arrays](https://github.com/adriantoine/enzyme-to-json/blob/master/tests/shallow.test.js#L161) are [missing some elements](https://github.com/adriantoine/enzyme-to-json/blob/master/tests/__snapshots__/shallow.test.js.snap#L111).

Would be happy to contribute, just want to understand if this is an issue with `enzyme-to-json` or `enzyme`'s [childrenOfNode](https://github.com/airbnb/enzyme/blob/29aab57bc2c2a7bb6e836b414ec47c1e9aa73e35/packages/enzyme/src/RSTTraversal.js#L11)?

**Comment by adriantoine** [comment]
Hey @donatasbacius,

Thanks for raising the bug!

I am not sure where it comes from and I don't have time to have a look right now, would you mind investigating?

**Comment by mshaaban088** [comment]
@donatasbacius I don't see the missing elements, so I'm wondering what did you expect and what did you see?

**Comment by donatasbacius** [comment]
@mshaaban088 - `<strong/>` tags are not rendered. See the snap file.

**Comment by mshaaban088** [comment]
@donatasbacius that's because it's shallow rendered, no?

**Comment by chris-pearce** [comment]
I'm also experiencing this bug, however, it's not 100% clear if it's related to `enzyme-to-json` but it's looking likely.

## To demonstrate

**JSX:**

```jsx
return [
  <h2 key="heading">Subscriptions</h2>,
  <ul key="list">
    {subscriptions.map(subscription => (
      <li key={subscription.id}>
        <strong>{subscription.name}</strong>
      </li>
    ))}
  </ul>,
];
```

**NOTE:** the JSX is wrapped in an array which we can do in React 16 (they recently released [`React.Fragment`](https://reactjs.org/docs/react-api.html#reactfragment)).

**Unit test:**

```js
it('renders correctly', () => {
  const tree = shallow(<Subscriptions {...props} />);
  expect(tree).toMatchSnapshot();
});
```

**Snapshot:**

```js
exports[`Subscriptions renders correctly 1`] = `
Array [
  <h2 
    key="heading" 
  />,
  <ul 
    key="list" 
  />,
]
`;
```

**NOTE:** child elements (including text nodes) are missing.

Removing the array in the component's `return` brings it back to normal, e.g.:

```jsx
return (
  <div>
    <h2>Subscriptions</h2>
    <ul>
      {subscriptions.map(subscription => (
        <li key={subscription.id}>
          <strong>{subscription.name}</strong>
        </li>
      ))}
    </ul>
  </div>
);
```

**Snapshot:**

```js
exports[`Subscriptions renders correctly 1`] = `
<div>
  <h2>
    Subscriptions
  </h2>
  <ul>
    <li
      key="1"
    >
      <strong>
        Richard Davis
      </strong>
    </li>
    <li
      key="2"
    >
      <strong>
        Johnathon Bailey
      </strong>
    </li>
    <li
      key="3"
    >
      <strong>
        Chris Donalds
      </strong>
    </li>
  </ul>
</div>
`;
```

**Comment by quicksnap** [comment]
I was looking into this, and it appears to be due to to how Enzyme's `wrapper.getNodeInternal()` is working: https://github.com/adriantoine/enzyme-to-json/blob/master/src/shallow.js#L73

As a nicer work around, if you're on React >16.2.0, consider replacing arrays with Fragments: https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

**Comment by VincentLanglet** [comment]
Enzyme issue then
