### ISSUE TITLE
Unexpected Token - Transpiling issues with Babel or other dependencies.

### ISSUE THREAD

**Issue by ramakay** [adriantoine/enzyme-to-json#92]
Hi There

Apologies in advance if this isn't per format or I should ask elsewhere.

I am having an issue as I progress towards moving a React 15.6.1 project to React 16. As part of this I have updated Babel, Chai, Enzyme etc. - When I run the test suite, I end up with the following:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token ','
  at webpack:///node_modules/enzyme-to-json/shallow.js:61:0 <- test-bundler.js:335732
```
The error is on this line:
https://github.com/adriantoine/enzyme-to-json/blob/v3.3.0/src/shallow.js#L48

Changing `node,` to  `node:node` resolves this error but it moves them to the next set of files.

It feels like a transpiling issue. 

test-bunder.js

```
import 'babel-polyfill';

import chai from 'chai';
import sinon from 'sinon';
import chaiEnzyme from 'chai-enzyme';
import sinonChai from 'sinon-chai';
import { matchSnapshot } from 'chai-karma-snapshot';

chai.use(chaiEnzyme());
chai.use(sinonChai);
chai.use(matchSnapshot);

global.sinon = sinon;
global.expect = chai.expect;

const context = require.context('../../app', true, /\.jsx?$/);
context.keys().forEach(context);
```

**Comment by madou** [comment]
what version of node are you using? using node 8 works for me.

**Comment by vlad-zhukov** [comment]
Is it [line 54](https://github.com/adriantoine/enzyme-to-json/blob/v3.3.0/src/shallow.js#L54) perhaps? Trailing commas in functions is a ES2017 feature, older engines do not support it.

**Comment by ramakay** [comment]
Node is v6.11.2 

@vlad-zhukov its https://github.com/adriantoine/enzyme-to-json/blob/v3.3.0/src/shallow.js#L48

**Comment by ramakay** [comment]
Upgraded to node v8.9.3 and using `babel preset-env` no luck

**Comment by aaron-ash** [comment]
@ramakay have you tried with different browser (chrome, firefox or safari)? Are you getting the same error?

**Comment by adriantoine** [comment]
Hi @ramakay,

Sorry for the delay, can you set up a repo to reproduce the error? 

It's a bit strange though we usually use `enzyme-to-json` with Jest, I haven't seen it working on Mocha/Chai but I'm happy to help if you set up a test repo.

**Comment by adriantoine** [comment]
I think I see what this is, in the compiled version of `enzyme-to-json` you have this code:
```js
var json = (0, _utils.applyMap)({
  node,
  type: (0, _utils.extractTypeName)(node),
  props: getProps(node, options),
  children: getChildren(node, options),
  $$typeof: Symbol.for('react.test.json')
}, options);
```
It's using the object shorthand properties which is [not supported by PhantomJS](https://kangax.github.io/compat-table/es6/#phantom).

I would recommend to generate your snapshot in a Node environment (`enzyme-to-json` supports all Node versions from v4) rather than PhantomJS.
