### ISSUE TITLE
PhantomJS: Unexpected token ',' issue 

### ISSUE THREAD

**Issue by Aakash-Goel** [adriantoine/enzyme-to-json#93]
I get below error in my test suite:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token ','
  at webpack:///node_modules/enzyme-to-json/shallow.js:61:0 <- test-bundler.js:335737
```
am using:
**"react": "16.2.0",
"enzyme": "3.2.0",
"enzyme-adapter-react-16": "1.1.0",
"enzyme-to-json": "3.3.0",**

Additional info:
my node version: v8.9.3
babel: 6.x
babel-preset-env: 1.6.x

After playing around i found that:
1. if i removed "enzyme-to-json" from my code base, test cases are running fine without any issues with PhantomJS.
2. if i choose Chrome, ChromeHeadless, Firefox, Safari, Puppeteer (except PhantomJS in my Karma config), my test cases are running fine. (so i don't think there's any transpiling issues).

So, i dug deeper and fix below 3 lines in 3 different files of `enzyme-to-json` package in my local node_modules, and my test cases with PhantomJS starts running.
1. enzyme-to-json/**shallow.js** (https://github.com/adriantoine/enzyme-to-json/blob/v3.3.0/src/shallow.js#L48):
original code = `node,`
replaced with: `node: node,`

2. enzyme-to-json/**mount.js** (https://github.com/adriantoine/enzyme-to-json/blob/master/src/mount.js#L57):
original code = `node,`
replaced with: `node: node,`

3. enzyme-to-json/**createSerializer.js** (https://github.com/adriantoine/enzyme-to-json/blob/master/src/createSerializer.js#L6)
original code = `test(wrapper) {`
replaced with = `test: function (wrapper) {`

Also, at (https://github.com/adriantoine/enzyme-to-json/blob/master/src/createSerializer.js#L9)
original code = `print(wrapper, serializer) {`
replaced with = `print: function (wrapper, serializer) {`

I am not sure where exactly the problem is.
Kindly, do let me know if am missing something here or any more information is required.

Thanks in advance.

**Comment by adriantoine** [comment]
Seems to be the exact same issue as #92, actually the error message is exactly the same one.
