### ISSUE TITLE
Passing into props an Array with elements wrapped in React.Fragment results in UNDEFINED nodes

### ISSUE THREAD

**Issue by wytrych** [adriantoine/enzyme-to-json#97]
Test case:
```jsx
import React from 'react';
import toJson from 'enzyme-to-json';
import { shallow } from 'enzyme';

const arr = [
  (
    <React.Fragment>One</React.Fragment>
  ),
  (
    <React.Fragment>Two</React.Fragment>
  ),
];

const TestComponent = function ({ options }) {
  return <div>{options[0]}</div>;
}

it('should not output UNDEFINED nodes', () => {
  const component = shallow(
    <div><TestComponent options={arr} /></div>
  );
  expect(toJson(component)).toMatchSnapshot();
});
```

Snapshot:

```

exports[`should not output UNDEFINED nodes 1`] = `
<div>
  <TestComponent
    options={
      Array [
        <UNDEFINED>
          One
        </UNDEFINED>,
        <UNDEFINED>
          Two
        </UNDEFINED>,
      ]
    }
  />
</div>
`;
```

**Comment by adriantoine** [comment]
Hi @wytrych, I'll have a look at your bug as soon as I can.

**Comment by wytrych** [comment]
Thank you!

**Comment by adriantoine** [comment]
Ok so the main isssue is actually not the array but passing a fragment as a prop, this is enough to reproduce the issue:

```js
it('should not output UNDEFINED nodes', () => {
  const component = shallow(
    <div><TestComponent options={<React.Fragment>Test</React.Fragment>} /></div>
  );
  expect(toJson(component)).toMatchSnapshot();
});
```

We support Fragment as children but not (yet) as props.

**Comment by adriantoine** [comment]
To follow up, I opened [an issue](https://github.com/facebook/jest/issues/5786) on the Jest repository and when [this PR](https://github.com/facebook/jest/pull/5816) gets merged and released, it should fix your issue.

I'll keep this issue open and close it when we can test the Jest fix and make sure it solves your issue.

**Comment by rickhanlonii** [comment]
Verified that https://github.com/facebook/jest/pull/5816 fixes the issue:

![](http://dp.hanlon.io/3m1l3j38372I/Image%202018-03-17%20at%207.51.39%20PM.png)

**Comment by wytrych** [comment]
That's really cool, thanks for taking it further @adriantoine

**Comment by adriantoine** [comment]
No problem, thanks @rickhanlonii for the fix!

**Comment by wytrych** [comment]
I guess we still need to wait for a new version of Jest to be released and then the package version updated here?

**Comment by adriantoine** [comment]
@wytrych you don't need to wait for a new version of `enzyme-to-json` just get the next Jest release which includes @rickhanlonii's fix.

**Comment by wytrych** [comment]
Ok thanks!
