### ISSUE TITLE
Unpublished version??

### ISSUE THREAD

**Issue by ifiokjr** [adriantoine/enzyme-to-json#98]
I"m getting this error when trying to install dependencies. I upgraded 4 hours ago to version `3.3.2` and now it seems to be breaking with the following error. 

```
error An unexpected error occurred: "Couldn't find any versions for \"enzyme-to-json\" that matches \"3.3.2\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ifiokjr/Coding/primarybid/PrimaryBid/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade-interactive for documentation about this command.
```

For now, I've downgraded to `3.3.1` as a temporary fix.

**Comment by hudochenkov** [comment]
Yesterday version 3.3.2 was published, which was containing breaking changes. Author contacted npm support to fix this mistake and they unpublished 3.3.2. https://github.com/adriantoine/enzyme-to-json/pull/91#issuecomment-371761772

**Comment by ifiokjr** [comment]
Okay, thanks. Closing, as most people wouldn't have seen it.

**Comment by adriantoine** [comment]
Hi @ifiokjr,

As @hudochenkov stated, I published this version as a patch version by mistake. Sorry for the inconvenience, rolling back to `3.3.1` is the right solution.
